== 게시글

=== 작성

operation::createArticle[snippets="http-request,request-body,request-fields,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
  {
    "code": "ALREADY_WRITTEN_ARTICLE_TITLE_AND_CATEGORY",
    "message": "해당 카테고리에 이미 작성된 글입니다. [카테고리: %s, 제목: %s]"
  }
]
----

=== 조회

operation::readArticle[snippets="path-parameters,http-request,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code": "NOT_FOUND_ARTICLE_ID",
      "message": "찾을 수 없는 게시글 번호입니다. [ID: %d]"
   }
]
----

=== 버전 목록 조회

operation::readArticleWithVersion[snippets="path-parameters,http-request,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
  {
    "code": "NOT_FOUND_ARTICLE_ID",
    "message": "찾을 수 없는 게시글 번호입니다. [ID: %d]"
  }
]
----

=== 해당 버전 조회

operation::readArticleByVersion[snippets="path-parameters,http-request,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
  {
    "code": "NOT_FOUND_ARTICLE_ID",
    "message": "찾을 수 없는 게시글 번호입니다. [ID: %d]"
  },
  {
    "code": "NOT_FOUND_ARTICLE_VERSION",
    "message": "찾을 수 없는 버전의 게시글 번호입니다. [ID: %d, 버전: %d]"
  }
]
----

=== 카테고리별 전체 조회

operation::readArticlesByCategory[snippets="http-request,http-response"]

=== 최근 편집

operation::readArticlesOrderByRecentEdits[snippets="http-request,http-response"]

=== 수정

operation::updateArticle[snippets="path-parameters,http-request,request-body,request-fields,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
  {
    "code": "NOT_FOUND_ARTICLE_ID",
    "message": "찾을 수 없는 게시글 번호입니다. [ID: %d]"
  }
]
----

=== 삭제

operation::deleteArticle[snippets="path-parameters,http-request,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
  {
    "code": "NOT_FOUND_ARTICLE_ID",
    "message": "찾을 수 없는 게시글 번호입니다. [ID: %d]"
  }
]
----